############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "About Us"
weight = 2

[[main]]
name = "Training"
weight = 3

[[main]]
weight = 4
name = "Resources"

[[main]]
weight = 5
name = "Student Corner"


[[main]]
parent = "About Us"
name = "Instructors"
pageRef = "/about/instructors"

[[main]]
parent = "About Us"
name = "Fleet"
pageRef = "/about/fleet"

[[main]]
parent = "About Us"
name = "Rates & Policies"
pageRef = "/about/rates-policies"

[[main]]
parent = "Training"
name = "Discovery Flights"
pageRef = "/training/discovery-flights"

[[main]]
parent = "Training"
name = "Private Pilot Training"
pageRef = "/training/private-pilot-training"

[[main]]
parent = "Training"
name = "Advanced Training"
pageRef = "/training/advanced-training"

[[main]]
parent = "Training"
name = "Foreflight and EFB Training"
pageRef = "/training/glass-cockpit"

[[main]]
parent = "Resources"
name = "Educational Materials"
pageRef = "/resources/educational-materials"

[[main]]
parent = "Resources"
name = "About Hobby Field"
pageRef = "/resources/hobby-field"

[[main]]
parent = "Resources"
name = "Medical Certification"
pageRef = "/resources/medical-certification"

[[main]]
parent = "Resources"
name = "Glossary"
pageRef = "/resources/glossary"

[[main]]
parent = "Student Corner"
name = "Media"
pageRef = "/student-corner/media"

[[main]]
parent = "Student Corner"
name = "Achievements"
pageRef = "/student-corner/achievements"

[[main]]
parent = "Student Corner"
name = "Testimonials"
pageRef = "/student-corner/testimonials"


# footer menu
[[footer]]
name = "Home"
pageRef = "/"
weight = 1


[[footer]]
name = "Site Map"
url = "/sitemap.xml"
weight = 2